---
title: "finalproj_lifeexpectancy"
author: "Noelle"
date: "12/2/2022"
output: html_document
---



```{r}
lifeData1 <- read.csv("Life_Expectancy_Data.csv")
lifeData1
```

```{r}
#data cleaup, remove all datapoints with NAs
lifeData = na.omit(lifeData1)
lifeData
```


```{r}
#hierarchical bayesian linear regression
#use nominal values to indicate year and status

#countries are clusters
#could compare using years as clusters vs countries as clusters
require(R2jags)

x0 = rep(0,length(lifeData$Year))
x1 = rep(0,length(lifeData$Year))
x2 = rep(0,length(lifeData$Year))
x3 = rep(0,length(lifeData$Year))
x4 = rep(0,length(lifeData$Year))
x5 = rep(0,length(lifeData$Year))
x6 = rep(0,length(lifeData$Year))
x7 = rep(0,length(lifeData$Year))
x8 = rep(0,length(lifeData$Year))
x9 = rep(0,length(lifeData$Year))
x10 = rep(0,length(lifeData$Year))
x11 = rep(0,length(lifeData$Year))
x12 = rep(0,length(lifeData$Year))
x13 = rep(0,length(lifeData$Year))
x14 = rep(0,length(lifeData$Year))
status = rep(0,length(lifeData$Year))

#set up dummy/index variables
#years 2000-2015, 16 year variables, all 1 = 2015
for (i in 1:length(lifeData$Year)) {
  x0[i] = ifelse(lifeData$Year[i] == 2000 || lifeData$Year[i]==2015,1,0)
  x1[i] = ifelse(lifeData$Year[i] == 2001 || lifeData$Year[i]==2015,1,0)
  x2[i] = ifelse(lifeData$Year[i] == 2002 || lifeData$Year[i]==2015,1,0)
  x3[i] = ifelse(lifeData$Year[i] == 2003 || lifeData$Year[i]==2015,1,0)
  x4[i] = ifelse(lifeData$Year[i] == 2004 || lifeData$Year[i]==2015,1,0)
  x5[i] = ifelse(lifeData$Year[i] == 2005 || lifeData$Year[i]==2015,1,0)
  x6[i] = ifelse(lifeData$Year[i] == 2006 || lifeData$Year[i]==2015,1,0)
  x7[i] = ifelse(lifeData$Year[i] == 2007 || lifeData$Year[i]==2015,1,0)
  x8[i] = ifelse(lifeData$Year[i] == 2008 || lifeData$Yea[i]==2015,1,0)
  x9[i] = ifelse(lifeData$Year[i] == 2009 || lifeData$Year[i]==2015,1,0)
  x10[i] = ifelse(lifeData$Year[i] == 2010 || lifeData$Year[i]==2015,1,0)
  x11[i] = ifelse(lifeData$Year[i] == 2011 || lifeData$Year[i]==2015,1,0)
  x12[i] = ifelse(lifeData$Year[i] == 2012 || lifeData$Year[i]==2015,1,0)
  x13[i] = ifelse(lifeData$Year[i] == 2013 || lifeData$Year[i]==2015,1,0)
  x14[i] = ifelse(lifeData$Year[i] == 2014 || lifeData$Year[i]==2015,1,0)
  status[i] = ifelse(lifeData$Status[i]=="Developing",1,0)
}
```


```{r}
#X_lhx6 = as.matrix(X_lhx6)
save.parms = c("beta","betay","mu")
life_expectancy.data = c("x0","x1","x2","x3","x4","x5","x6","x7","x8","x9","x10","x11","x12","x13","x14","y","mortality","infant_deaths","alcohol", "status",
                         "percExp","hepB","measles","BMI","under5Deaths","polio","totalExp","dipth","hivaids","gdp","pop","thin1019","thin59",
                         "incomeComp","school","N","J","indices")
mortality = lifeData$"Adult.Mortality"
infant_deaths = lifeData$"infant.deaths"
alcohol = lifeData$"Alcohol"
percExp = lifeData$"percentage.expenditure"
hepB = lifeData$"Hepatitis.B"
measles = lifeData$"Measles"
BMI = lifeData$"BMI"
under5Deaths = lifeData$"under.five.deaths"
polio = lifeData$"Polio"
totalExp = lifeData$"Total.expenditure"
dipth = lifeData$"Diphtheria"
hivaids = lifeData$"HIV.AIDS"
gdp = lifeData$"GDP"
pop = lifeData$"Population"
thin1019 = lifeData$"thinness..1.19.years"
thin59 = lifeData$"thinness.5.9.years"
incomeComp = lifeData$"Income.composition.of.resources"
school = lifeData$"Schooling"
y = lifeData$"Life.expectancy"
N = length(lifeData$Country) #go through each point
J = length(unique(lifeData$Country)) #go through each country
ident = diag(35)


```

```{r}
#assign a column of indices, each cluster has its own unique index
#so 193 indices
indicesDict = c(unique(lifeData$Country))
indices = rep(0,N)
for (i in 1:N) {
  indices[i] = which(indicesDict==lifeData$Country[i])
}
```


```{r}
#MODEL
#use wishart for variance of covariates in the beginning, uninformative prior
life_expectancy.model = function()
{
  for (i in 1:N) {
     y[i] ~ dnorm(mu[indices[i],i],tau)
     #indices[i] gets the cluster number
     #intercept + year_covariates * x0 through x14 + developing_covairate * developing + ...
     mu[indices[i],i] <- 
          betay[indices[i],1] #intercept
          + betay[indices[i],2]*x0[i] #year 2000
          + betay[indices[i],3]*x1[i] #year 2001
          + betay[indices[i],4]*x2[i] #year 2002
          + betay[indices[i],5]*x3[i] #2003
          + betay[indices[i],6]*x4[i] #2004
          + betay[indices[i],7]*x5[i] #2005
          + betay[indices[i],8]*x6[i] #2005
          + betay[indices[i],9]*x7[i] #2007
          + betay[indices[i],10]*x8[i] #2008
          + betay[indices[i],11]*x9[i] #2009
          + betay[indices[i],12]*x10[i] #2010
          + betay[indices[i],13]*x11[i] #2011
          + betay[indices[i],14]*x12[i] #2012
          + betay[indices[i],15]*x13[i] #2013
          + betay[indices[i],16]*x14[i] #2014
          + betay[indices[i],17]*mortality[i] #mortality
          + betay[indices[i],18]*infant_deaths[i] #infant_deaths
          + betay[indices[i],19]*alcohol[i] #alcohol
          + betay[indices[i],20]*percExp[i] #percentage expenditure
          + betay[indices[i],21]*hepB[i] #hepatitis B
          + betay[indices[i],22]*measles[i] #meases
          + betay[indices[i],23]*BMI[i] #BMI 
          + betay[indices[i],24]*under5Deaths[i] #under 5 deaths
          + betay[indices[i],25]*polio[i] #Polio
          + betay[indices[i],26]*totalExp[i] #total expenditure
          + betay[indices[i],27]*dipth[i] #diptheria
          + betay[indices[i],28]*hivaids[i] #hiv.aids
          + betay[indices[i],29]*gdp[i] #gdp
          + betay[indices[i],30]*pop[i] #population
          + betay[indices[i],31]*thin1019[i] #thinness relevance 10-19 yrs old
          + betay[indices[i],32]*thin59[i] #thinness relevance 5-9 yrs old
          + betay[indices[i],33]*incomeComp[i] #income composition
          + betay[indices[i],34]*school[i] #years of schooling
          + betay[indices[i],35]*status[i] #status, developing or not
  }
  for (j in 1:J) {
    for (k in 1:35) {
      betay[j,k] ~dnorm(beta[k],P)
    }
    #betay[j,1:34] ~ dnorm(beta[1:34],P)
  }      
  for (k in 1:35) {
    beta[k] ~dnorm(0,1e-6)
  }
   tau ~ dgamma(1e-6,1e-6)
   P ~ dgamma(1e-6,1e-6)
   
  #P[1:34,1:34] ~ dwish(ident,3)
}

```


```{r}
life_expectancy.out = jags(data=life_expectancy.data,parameters.to.save=save.parms,model.file=life_expectancy.model,
                n.chains=3,n.iter=10000,n.burnin=5000,n.thin=1)
print(life_expectancy.out,digits=5)
```

